---
- name: check deploy file 
  stat: 
    path: "{{version_dir}}/{{version}}/app/cstp-dp-ds"
  register: cstp_dp_ds_file

- import_tasks: update_cstp_dp_ds.yml
  when: (cstp_dp_ds_file.stat.exists) and (inventory_hostname in groups['CSTP_DP_DS'])