---
- name: create {{version}}  backup directory
  file:
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}"
    state: directory


- name: stop cstp-dp-ds services
  shell: |
    source ~/.bash_profile;
    set -m; ./app.sh stop
  args:
    chdir:
      "{{ansible_env.HOME}}/app/cstp-dp-ds/bin/"
  ignore_errors: true


- name: check cstp-dp-ds app
  stat:
    path: "{{ansible_env.HOME}}/app/cstp-dp-ds"
  register: cstp_dp_ds_status

- name: check cstp-dp-ds backup
  stat:
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/cstp-dp-ds_{{version}}"
  register: cstp_dp_ds_backup_status


- name: backup cstp-dp-ds
  shell: |

    tar -czf {{ansible_env.HOME}}/upgrade/backup/{{version}}/cstp-dp-ds.tgz  cstp-dp-ds --exclude=cstp-dp-ds/logs/*
    touch {{ansible_env.HOME}}/upgrade/backup/{{version}}/cstp-dp-ds_{{version}}
  args:
    chdir: "{{ansible_env.HOME}}/app/"
  when: (cstp_dp_ds_status.stat.exists) and (cstp_dp_ds_backup_status.stat.exists == False)


- name: save new app name
  shell: |
    echo -e "cstp-dp-ds/ \n" >> "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"
  when: cstp_dp_ds_status.stat.exists == False

- name: create cstp-dp-ds directory
  file:
    path: "{{ansible_env.HOME}}/app/cstp-dp-ds"
    state: directory

- name: rm CSTP_DP_DS old file
  file:
    path: "{{ansible_env.HOME}}/app/cstp-dp-ds/{{item}}"
    state: absent
  with_items:
      - conf
      - lib





- name: update cstp-dp-ds app
  shell: |
    cp -r {{version_dir}}/{{version}}/app/cstp-dp-ds   {{ansible_env.HOME}}/app/


- name: unix2dos config
  shell: |
     unix2dos ./*
  args:
    chdir: "{{ansible_env.HOME}}/app/cstp-dp-ds/conf/"




- name: start cstp-dp-ds services
  shell: |
    source ~/.bash_profile;
    set -m; ./app.sh start
  args:
    chdir:
      "{{ansible_env.HOME}}/app/cstp-dp-ds/bin/"

- name: wait service start
  wait_for:
    timeout: 10

- name: check cstp-dp-ds services
  shell: |
    ps -ef | grep RMBCSTP_CSTP_DS |grep -iv grep 
  register: cstp_dp_ds_services

- name: show cstp-dp-ds services status
  debug:
    msg: "{{cstp_dp_ds_services.stdout_lines}}"


