---
- name: check deploy file 
  stat: 
    path: "{{version_dir}}/{{version}}/Server/ApacheTomcat7_BCCL"
  register: BCCL_file

- import_tasks: update_BCCL.yml
  when: (BCCL_file.stat.exists) and (inventory_hostname in groups['BCCL'])