---
- name: check deploy file 
  stat: 
    path: "{{version_dir}}/{{version}}/imixapp/IMIXCSTP"
  register: IMIXCSTP_file

- import_tasks: update_IMIXCSTP.yml
  when: (IMIXCSTP_file.stat.exists) and (inventory_hostname in groups['IMIXCSTP'])