---
- name: check deploy file 
  stat: 
    path: "{{version_dir}}/{{version}}/app/cstp-dp-cbt"
  register: cstp_dp_cbt_file

- import_tasks: update_cstp_dp_cbt.yml
  when: (cstp_dp_cbt_file.stat.exists) and (inventory_hostname in groups['CSTP_DP_CBT'])