---
- name: check deploy file 
  stat: 
    path: "{{version_dir}}/{{version}}/app/cstp-dp-irs"
  register: cstp_dp_irs_file

- import_tasks: update_cstp_dp_irs.yml
  when: (cstp_dp_irs_file.stat.exists) and (inventory_hostname in groups['CSTP_DP_IRS'])