---
- name: check new application file
  stat:
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"
  register: new_application_status

- name: read new application file
  shell: |
      cat "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"  |grep -v grep
  register: new_application_file
  when: new_application_status.stat.exists


- name: clear new application
  block:
    - name: stop CSTPReport services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/Report/CSTPReport/"
      ignore_errors: true
      when: (new_application_file.stdout.find("CSTPReport/") != -1  )
    


    - name: delete CSTPReport directory
      file:
        path: "{{ansible_env.HOME}}/Report/CSTPReport"
        state: absent
      when: (new_application_file.stdout.find("CSTPReport/") != -1  )
  when: new_application_status.stat.exists

- name: check CSTPReport {{version}} backup
  stat: 
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/CSTPReport.tgz"
  register: CSTPReport_backup




- name: start rollback EXCHANGEReport
  block:

    - name: stop CSTPReport services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/Report/CSTPReport/"
      ignore_errors: true
    


    

    - name: delete CSTPReport directory
      shell: |
        find {{ansible_env.HOME}}/Report/CSTPReport/*  -maxdepth 0  ! -path '{{ansible_env.HOME}}/Report/CSTPReport/Log*'  -exec     rm -rf {} \;
      ignore_errors: true


    
    - name: rollback CSTPReport app
      unarchive:
        src: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/CSTPReport.tgz"
        dest: "{{ansible_env.HOME}}/Report/"
        remote_src: yes
        mode: 0755
    
        
    
    - name: start CSTPReport services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh start
      args:
        chdir:
          "{{ansible_env.HOME}}/Report/CSTPReport/"
    
    - name: wait service start
      wait_for:
        timeout: 10
    
    - name: check CSTPReport services
      shell: |
        ps -ef | grep CSTP_Report_CSTP
      register: CSTPReport_services
    
    - name: show CSTPReport services status
      debug:
        msg: "{{CSTPReport_services.stdout_lines}}"
    
    
  when: CSTPReport_backup.stat.exists
