---
- name: check new application file
  stat:
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"
  register: new_application_status

- name: read new application file
  shell: |
      cat "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"  |grep -v grep
  register: new_application_file
  when: new_application_status.stat.exists


- name: clear new application
  block:
    - name: stop IMIXCSTP services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/imixapp/IMIXCSTP/"
      ignore_errors: true
      when: (new_application_file.stdout.find("IMIXCSTP/") != -1  )
    
    
    - name: delete IMIXCSTP directory
      file:
        path: "{{ansible_env.HOME}}/imixapp/IMIXCSTP"
        state: absent
      when: (new_application_file.stdout.find("IMIXCSTP/") != -1  )
  when: new_application_status.stat.exists


- name: check IMIXCSTP {{version}} backup
  stat: 
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/IMIXCSTP.tgz"
  register: IMIXCSTP_backup






- name: start rollback IMIXCSTP
  block:
    - name: stop IMIXCSTP services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/imixapp/IMIXCSTP/"
      ignore_errors: true
    
    
    - name: delete IMIXCSTP directory
      file:
        path: "{{ansible_env.HOME}}/imixapp/IMIXCSTP"
        state: absent
    
    - name: delete IMIXCSTP directory
      shell: |
        find {{ansible_env.HOME}}/imixapp/IMIXCSTP/*  -maxdepth 0  ! -path '{{ansible_env.HOME}}/imixapp/IMIXCSTP/Log*'  -exec     rm -rf {} \;
      ignore_errors: true
    
    
    
    
    - name: rollback IMIXCSTP app
      unarchive:
        src: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/IMIXCSTP.tgz"
        dest: "{{ansible_env.HOME}}/imixapp/"
        remote_src: yes
        mode: 0755
    
    
    - name: start IMIXCSTP services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh start
      args:
        chdir:
          "{{ansible_env.HOME}}/imixapp/IMIXCSTP/"
    
    - name: wait service start
      wait_for:
        timeout: 10
    
    - name: check IMIXCSTP services
      shell: |
        ps -ef | grep CSTP_IMIX_CSTP
      register: IMIXCSTP_services
    
    - name: show IMIXCSTP services status
      debug:
        msg: "{{IMIXCSTP_services.stdout_lines}}"
    
  when: IMIXCSTP_backup.stat.exists
