---
- name: check new application file
  stat:
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"
  register: new_application_status

- name: read new application file
  shell: |
      cat "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"  |grep -v grep
  register: new_application_file
  when: new_application_status.stat.exists


- name: clear new application
  block:
    - name: stop CSTP_PROCESSOR services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/imixapp/CSTP_PROCESSOR/"
      ignore_errors: true
      when: (new_application_file.stdout.find("CSTP_PROCESSOR/") != -1  )


    
    - name: delete CSTP_PROCESSOR directory
      file:
        path: "{{ansible_env.HOME}}/imixapp/CSTP_PROCESSOR"
        state: absent
      when: (new_application_file.stdout.find("CSTP_PROCESSOR/") != -1  )
  when: new_application_status.stat.exists

- name: check CSTP_PROCESSOR {{version}} backup
  stat: 
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/CSTP_PROCESSOR.tgz"
  register: CSTP_PROCESSOR_backup






- name: start rollback CSTP_PROCESSOR
  block:

    - name: stop CSTP_PROCESSOR services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/imixapp/CSTP_PROCESSOR/"
      ignore_errors: true
    
        
    
    - name: delete CSTP_PROCESSOR directory
      shell: |
        find {{ansible_env.HOME}}/imixapp/CSTP_PROCESSOR/*  -maxdepth 0  ! -path '{{ansible_env.HOME}}/imixapp/CSTP_PROCESSOR/Log*'  -exec     rm -rf {} \;
      ignore_errors: true

    
    
    - name: rollback CSTP_PROCESSOR app
      unarchive:
        src: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/CSTP_PROCESSOR.tgz"
        dest: "{{ansible_env.HOME}}/imixapp/"
        remote_src: yes
        mode: 0755
 
    
    
    - name: start CSTP_PROCESSOR services
      shell: |
        source ~/.bash_profile;
        set -m; ./app.sh start
      args:
        chdir:
          "{{ansible_env.HOME}}/imixapp/CSTP_PROCESSOR/"
    
    - name: wait service start
      wait_for:
        timeout: 10
    
    - name: check CSTP_PROCESSOR services
      shell: |
        ps -ef | grep CSTP_PROCESSOR 
      register: CSTP_PROCESSOR_services
    
    - name: show CSTP_PROCESSOR services status
      debug:
        msg: "{{CSTP_PROCESSOR_services.stdout_lines}}"
    
    

  when: CSTP_PROCESSOR_backup.stat.exists
