---
- name: check new application file
  stat:
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"
  register: new_application_status

- name: read new application file
  shell: |
      cat "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"  |grep -v grep
  register: new_application_file
  when: new_application_status.stat.exists


- name: clear new application
  block:
    - name: stop cstp-dp-dsbccl services
      shell: |
        source ~/.bash_profile;
        set -m; sh ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/app/cstp-dp-dsbccl/bin/"
      ignore_errors: true
      when: (new_application_file.stdout.find("cstp-dp-dsbccl/") != -1  )


    - name: delete cstp-dp-dsbccl directory
      file:
        path: "{{ansible_env.HOME}}/app/cstp-dp-dsbccl"
        state: absent
      when: (new_application_file.stdout.find("cstp-dp-dsbccl/") != -1  )
  when: new_application_status.stat.exists

- name: check cstp-dp-dsbccl {{version}} backup
  stat: 
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/cstp-dp-dsbccl.tgz"
  register: cstp_dp_dsbccl_backup

- name: start rollback cstp-dp-dsbccl
  block:


    - name: stop cstp-dp-dsbccl services
      shell: |
        source ~/.bash_profile;
        set -m; sh ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/app/cstp-dp-dsbccl/bin/"
      ignore_errors: true
    
    - name: delete cstp-dp-dsbccl directory
      file:
        path: "{{ansible_env.HOME}}/app/cstp-dp-dsbccl/bin"
        state: absent
    
    - name: delete cstp-dp-dsbccl directory
      shell: |
        find {{ansible_env.HOME}}/app/cstp-dp-dsbccl/*  -maxdepth 0  ! -path '{{ansible_env.HOME}}/app/cstp-dp-dsbccl/logs*'  -exec     rm -rf {} \;
      ignore_errors: true
    
    
    
    
    - name: rollback cstp-dp-dsbccl app
      unarchive:
        src: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/cstp-dp-dsbccl.tgz"
        dest: "{{ansible_env.HOME}}/app/"
        remote_src: yes
        mode: 0755

    - name: start cstp-dp-dsbccl services
      shell: |
        source ~/.bash_profile;
        set -m; sh ./app.sh start
      args:
        chdir:
          "{{ansible_env.HOME}}/app/cstp-dp-dsbccl/bin/"
    
    - name: wait service start
      wait_for:
        timeout: 10
    
    - name: check cstp-dp-dsbccl services
      shell: |
        ps -ef | grep RMBCSTP_BCCL_DS
      register: cstp_dp_dsbccl_services
    
    - name: show cstp-dp-dsbccl services status
      debug:
        msg: "{{cstp_dp_dsbccl_services.stdout_lines}}"
    
    
  when: cstp_dp_dsbccl_backup.stat.exists

