---
- name: check new application file
  stat:
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"
  register: new_application_status

- name: read new application file
  shell: |
      cat "{{ansible_env.HOME}}/upgrade/backup/{{version}}/new_application"  |grep -v grep
  register: new_application_file
  when: new_application_status.stat.exists


- name: clear new application
  block:
    - name: stop cstp-dp-emergency services
      shell: |
        source ~/.bash_profile;
        set -m; sh ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/app-web/cstp-dp-emergency/bin/"
      ignore_errors: true
      when: (new_application_file.stdout.find("cstp-dp-emergency/") != -1  )

    
    - name: delete cstp-dp-emergency directory
      file:
        path: "{{ansible_env.HOME}}/app-web/cstp-dp-emergency"
        state: absent
      when: (new_application_file.stdout.find("cstp-dp-emergency/") != -1  )
  when: new_application_status.stat.exists

- name: check cstp-dp-emergency {{version}} backup
  stat: 
    path: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/cstp-dp-emergency.tgz"
  register: cstp_dp_emergency_backup

- name: start rollback cstp-dp-emergency
  block:


    - name: stop cstp-dp-emergency services
      shell: |
        source ~/.bash_profile;
        set -m; sh ./app.sh stop
      args:
        chdir:
          "{{ansible_env.HOME}}/app-web/cstp-dp-emergency/bin/"
      ignore_errors: true

    
    - name: delete cstp-dp-emergency directory
      file:
        path: "{{ansible_env.HOME}}/app-web/cstp-dp-emergency"
        state: absent
    
    - name: delete cstp-dp-dsbccl directory
      shell: |
        find {{ansible_env.HOME}}/app/cstp-dp-dsbccl/*  -maxdepth 0  ! -path '{{ansible_env.HOME}}/app/cstp-dp-dsbccl/logs*'  -exec     rm -rf {} \;
      ignore_errors: true
    
    
    
    
    - name: rollback cstp-dp-emergency app
      unarchive:
        src: "{{ansible_env.HOME}}/upgrade/backup/{{version}}/cstp-dp-emergency.tgz"
        dest: "{{ansible_env.HOME}}/app-web/"
        remote_src: yes
        mode: 0755

    
        
    - name: start cstp-dp-emergency services
      shell: |
        source ~/.bash_profile;
        set -m; sh ./app.sh start
      args:
        chdir:
          "{{ansible_env.HOME}}/app-web/cstp-dp-emergency/bin/"
    
    - name: wait service start
      wait_for:
        timeout: 10
    
    - name: check cstp-dp-emergency services
      shell: |
        ps -ef | grep CSTP_EMERGENCY
      register: cstp_dp_emergency_services
    
    - name: show cstp-dp-emergency services status
      debug:
        msg: "{{cstp_dp_emergency_services.stdout_lines}}"
    
    
  when: cstp_dp_emergency_backup.stat.exists

