---
- name: check deploy file 
  stat: 
    path: "{{version_dir}}/{{version}}/app-web/cstp-dp-emergency"
  register: cstp_dp_emergency_file

- import_tasks: update_cstp_dp_emergency.yml
  when: (cstp_dp_emergency_file.stat.exists) and (inventory_hostname in groups['CSTP_DP_EMERGENCY'])