---
- name: rm old backupDB directory
  file:
      path: "{{ansible_env.HOME}}/backupDB/"
      state: absent


- name: create backupDB directory
  file:
    path: "{{ansible_env.HOME}}/backupDB/"
    state: directory


- name: copy bakcupDB scripts
  copy:
    src: "{{version_dir}}/DATABASE/{{version}}"
    dest: "{{ansible_env.HOME}}/backupDB/"
    mode: 0755


- name: update backupDB scripts config
  lineinfile:
    path: "{{ansible_env.HOME}}/backupDB/{{version}}/backupDB.sh"
    regexp: "{{item.key}}"
    line: "{{item.value}}"
  with_items:
      - {key: user,value: "{{CSTPDBuser}}"}
      - {key: password,value: "{{CSTPDBpassword}}"}


- name: start backupDB scripts
  shell: |

    set -m;sh backupDB.sh
  args:
    chdir: "{{version_dir}}/backupDB/{{version}}/"

