---
- name: check deploy file 
  stat: 
    path: "{{version_dir}}/{{version}}/app/cstp-dp-dsbccl"
  register: cstp_dp_dsbccl_file

- import_tasks: update_cstp_dp_dsbccl.yml
  when: (cstp_dp_dsbccl_file.stat.exists) and (inventory_hostname in groups['CSTP_DP_DSBCCL'])